version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ['nodejs']
  plugins = ['react', 'vue']
  dialect = 'flow'
  dependency_file_paths = [
    'packages/demo-react/',
    'packages/demo-vue'
  ]

[[transformers]]
    name = "prettier"
    enabled = true
