version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ['nodejs']
  plugins = ['react', 'angular']
  dialect = 'flow'
  dependency_file_paths = [
    'packages/demo-angular/'
  ]

[[transformers]]
    name = "prettier"
    enabled = true